# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.6'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: 'CafeAPI-Angular'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'CafeAPI-Angular/dist/CafeAPI-Angular'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(1)(2c1de073-9f0b-4613-9eea-d9b009bdd0a8)'
    appType: 'webApp'
    WebAppName: 'CafeAPI-Angular'
    packageForLinux: 'Container'

    